// Placeholder component registry
// This file is normally generated by a script.
// Currently using a placeholder to allow the build to pass.

import { ComponentType } from 'react';

export const ComponentRegistry: Record<string, ComponentType<any>> = {};
