
// Auto-generated by scripts/scan-structure.ts
import { lazy, ComponentType, LazyExoticComponent } from 'react';

export const ComponentRegistry: Record<string, LazyExoticComponent<ComponentType<any>>> = {
  'toggle': lazy(() => import('@repo/ui/toggle').then((m: any) => ({ default: m.Toggle || m.toggle || m.default }))),
  'toggle-group': lazy(() => import('@repo/ui/toggle-group').then((m: any) => ({ default: m.ToggleGroup || m.togglegroup || m.default }))),
  'textarea': lazy(() => import('@repo/ui/textarea').then((m: any) => ({ default: m.Textarea || m.textarea || m.default }))),
  'table': lazy(() => import('@repo/ui/table').then((m: any) => ({ default: m.Table || m.table || m.default }))),
  'switch': lazy(() => import('@repo/ui/switch').then((m: any) => ({ default: m.Switch || m.switch || m.default }))),
  'scroll-area': lazy(() => import('@repo/ui/scroll-area').then((m: any) => ({ default: m.ScrollArea || m.scrollarea || m.default }))),
  'auth-context': lazy(() => import('@repo/ui/auth-context').then((m: any) => ({ default: m.AuthContext || m.authcontext || m.default }))),
};
