-- Vehicle aggregation functions for DDPC discover page
-- These functions need to be created in Supabase SQL editor

-- Function to get unique vehicles grouped by year/make/model with proper sorting
CREATE OR REPLACE FUNCTION get_unique_vehicles(limit_param integer DEFAULT 50, offset_param integer DEFAULT 0)
RETURNS TABLE(
  id text,
  make text,
  model text,
  year text,
  "trim" text,
  trim_description text,
  base_msrp text,
  base_invoice text,
  colors_exterior text,
  colors_interior text,
  body_type text,
  doors text,
  total_seating text,
  length_in text,
  width_in text,
  height_in text,
  wheelbase_in text,
  front_track_in text,
  rear_track_in text,
  ground_clearance_in text,
  angle_of_approach_deg text,
  angle_of_departure_deg text,
  turning_circle_ft text,
  drag_coefficient_cd text,
  epa_interior_volume_cuft text,
  cargo_capacity_cuft text,
  max_cargo_capacity_cuft text,
  curb_weight_lbs text,
  gross_weight_lbs text,
  max_payload_lbs text,
  max_towing_capacity_lbs text,
  cylinders text,
  engine_size_l text,
  horsepower_hp text,
  horsepower_rpm text,
  torque_ft_lbs text,
  torque_rpm text,
  valves text,
  valve_timing text,
  cam_type text,
  drive_type text,
  transmission text,
  engine_type text,
  fuel_type text,
  fuel_tank_capacity_gal text,
  epa_combined_mpg text,
  epa_city_highway_mpg text,
  range_miles_city_hwy text,
  epa_combined_mpge text,
  epa_city_highway_mpge text,
  epa_electric_range_mi text,
  epa_kwh_per_100mi text,
  epa_charge_time_240v_hr text,
  battery_capacity_kwh text,
  front_head_room_in text,
  front_hip_room_in text,
  front_leg_room_in text,
  front_shoulder_room_in text,
  rear_head_room_in text,
  rear_hip_room_in text,
  rear_leg_room_in text,
  rear_shoulder_room_in text,
  warranty_basic text,
  warranty_drivetrain text,
  warranty_roadside text,
  warranty_rust text,
  source_json text,
  source_url text,
  image_url text,
  review text,
  pros text,
  cons text,
  whats_new text,
  nhtsa_overall_rating text,
  new_price_range text,
  used_price_range text,
  scorecard_overall text,
  scorecard_driving text,
  scorecard_confort text,
  scorecard_interior text,
  scorecard_utility text,
  scorecard_technology text,
  expert_verdict text,
  expert_performance text,
  expert_comfort text,
  expert_interior text,
  expert_technology text,
  expert_storage text,
  expert_fuel_economy text,
  expert_value text,
  expert_wildcard text,
  old_trim text,
  old_description text,
  images_url text,
  suspension text,
  front_seats text,
  rear_seats text,
  power_features text,
  instrumentation text,
  convenience text,
  comfort text,
  memorized_settings text,
  in_car_entertainment text,
  roof_and_glass text,
  body text,
  truck_features text,
  tires_and_wheels text,
  doors_features text,
  towing_and_hauling text,
  safety_features text,
  packages text,
  exterior_options text,
  interior_options text,
  mechanical_options text,
  country_of_origin text,
  car_classification text,
  platform_code_generation text,
  date_added text,
  new_make text,
  new_model text,
  new_year text
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT DISTINCT ON (vd.year, vd.make, vd.model)
    vd.id,
    vd.make,
    vd.model,
    vd.year,
    vd."trim",
    vd.trim_description,
    vd.base_msrp,
    vd.base_invoice,
    vd.colors_exterior,
    vd.colors_interior,
    vd.body_type,
    vd.doors,
    vd.total_seating,
    vd.length_in,
    vd.width_in,
    vd.height_in,
    vd.wheelbase_in,
    vd.front_track_in,
    vd.rear_track_in,
    vd.ground_clearance_in,
    vd.angle_of_approach_deg,
    vd.angle_of_departure_deg,
    vd.turning_circle_ft,
    vd.drag_coefficient_cd,
    vd.epa_interior_volume_cuft,
    vd.cargo_capacity_cuft,
    vd.max_cargo_capacity_cuft,
    vd.curb_weight_lbs,
    vd.gross_weight_lbs,
    vd.max_payload_lbs,
    vd.max_towing_capacity_lbs,
    vd.cylinders,
    vd.engine_size_l,
    vd.horsepower_hp,
    vd.horsepower_rpm,
    vd.torque_ft_lbs,
    vd.torque_rpm,
    vd.valves,
    vd.valve_timing,
    vd.cam_type,
    vd.drive_type,
    vd.transmission,
    vd.engine_type,
    vd.fuel_type,
    vd.fuel_tank_capacity_gal,
    vd.epa_combined_mpg,
    vd.epa_city_highway_mpg,
    vd.range_miles_city_hwy,
    vd.epa_combined_mpge,
    vd.epa_city_highway_mpge,
    vd.epa_electric_range_mi,
    vd.epa_kwh_per_100mi,
    vd.epa_charge_time_240v_hr,
    vd.battery_capacity_kwh,
    vd.front_head_room_in,
    vd.front_hip_room_in,
    vd.front_leg_room_in,
    vd.front_shoulder_room_in,
    vd.rear_head_room_in,
    vd.rear_hip_room_in,
    vd.rear_leg_room_in,
    vd.rear_shoulder_room_in,
    vd.warranty_basic,
    vd.warranty_drivetrain,
    vd.warranty_roadside,
    vd.warranty_rust,
    vd.source_json,
    vd.source_url,
    vd.image_url,
    vd.review,
    vd.pros,
    vd.cons,
    vd.whats_new,
    vd.nhtsa_overall_rating,
    vd.new_price_range,
    vd.used_price_range,
    vd.scorecard_overall,
    vd.scorecard_driving,
    vd.scorecard_confort,
    vd.scorecard_interior,
    vd.scorecard_utility,
    vd.scorecard_technology,
    vd.expert_verdict,
    vd.expert_performance,
    vd.expert_comfort,
    vd.expert_interior,
    vd.expert_technology,
    vd.expert_storage,
    vd.expert_fuel_economy,
    vd.expert_value,
    vd.expert_wildcard,
    vd.old_trim,
    vd.old_description,
    vd.images_url,
    vd.suspension,
    vd.front_seats,
    vd.rear_seats,
    vd.power_features,
    vd.instrumentation,
    vd.convenience,
    vd.comfort,
    vd.memorized_settings,
    vd.in_car_entertainment,
    vd.roof_and_glass,
    vd.body,
    vd.truck_features,
    vd.tires_and_wheels,
    vd.doors_features,
    vd.towing_and_hauling,
    vd.safety_features,
    vd.packages,
    vd.exterior_options,
    vd.interior_options,
    vd.mechanical_options,
    vd.country_of_origin,
    vd.car_classification,
    vd.platform_code_generation,
    vd.date_added,
    vd.new_make,
    vd.new_model,
    vd.new_year
  FROM vehicle_data vd
  ORDER BY
    vd.year::integer DESC,
    vd.make ASC,
    vd.model ASC,
    vd."trim" ASC  -- For consistent selection within groups
  LIMIT limit_param
  OFFSET offset_param;
END;
$$;

-- Function to get comprehensive filter options from all vehicle data
CREATE OR REPLACE FUNCTION get_vehicle_filter_options()
RETURNS json
LANGUAGE plpgsql
AS $$
DECLARE
  result json;
BEGIN
  SELECT json_build_object(
    'years', ARRAY(SELECT DISTINCT year::integer FROM vehicle_data ORDER BY year::integer DESC),
    'makes', ARRAY(SELECT DISTINCT make FROM vehicle_data ORDER BY make ASC),
    'models', ARRAY(SELECT DISTINCT model FROM vehicle_data ORDER BY model ASC),
    'engineTypes', ARRAY(SELECT DISTINCT cylinders FROM vehicle_data WHERE cylinders IS NOT NULL ORDER BY cylinders ASC),
    'fuelTypes', ARRAY(SELECT DISTINCT fuel_type FROM vehicle_data WHERE fuel_type IS NOT NULL ORDER BY fuel_type ASC),
    'drivetrains', ARRAY(SELECT DISTINCT drive_type FROM vehicle_data WHERE drive_type IS NOT NULL ORDER BY drive_type ASC),
    'bodyTypes', ARRAY(SELECT DISTINCT body_type FROM vehicle_data WHERE body_type IS NOT NULL ORDER BY body_type ASC)
  ) INTO result;

  RETURN result;
END;
$$;
