
import { scanStructureData, toPascalCase } from '../src/lib/structure-scanner';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Resolve relative to the script location (apps/web/scripts)
const WEB_ROOT = path.resolve(__dirname, '..');
const OUTPUT_FILE = path.join(WEB_ROOT, 'src/lib/component-registry.ts');
const SQL_OUTPUT_FILE = path.join(WEB_ROOT, 'seed_structure.sql');

async function runScript() {
  console.log('Running structure scan script...');

  // Use the shared scanner
  // Note: scanStructureData defaults to process.cwd(), but since we are running via tsx from root likely, or inside scripts...
  // We explicitly pass the calculated WEB_ROOT to ensure consistency regardless of CWD.
  const items = await scanStructureData({
    webRoot: WEB_ROOT
  });

  const registry: string[] = [];
  const sqlStatements: string[] = [];

  // Truncate table first (Legacy behavior for the SQL seed file)
  sqlStatements.push('TRUNCATE TABLE app_structure;');

  for (const item of items) {
    // Generate SQL
    // Escape single quotes in names/paths just in case
    const safeName = item.name.replace(/'/g, "''");
    const safePath = item.path.replace(/'/g, "''");
    const metadataJson = JSON.stringify(item.metadata).replace(/'/g, "''");

    sqlStatements.push(`INSERT INTO app_structure (id, name, type, path, last_updated, metadata, status) VALUES ('${item.id}', '${safeName}', '${item.type}', '${safePath}', NOW(), '${metadataJson}', 'active');`);

    // Generate Registry Entry (Components only)
    if (item.type === 'component') {
      const pascalName = toPascalCase(item.name);
      const safeNameKey = item.name.replace(/[^a-zA-Z0-9]/g, '');
      const importPath = item.path; // already formatted as @repo/ui/...

      registry.push(`  '${item.name}': lazy(() => import('${importPath}').then((m: any) => ({ default: m.${pascalName} || m.${safeNameKey} || m.default }))),`);
    }
  }

  // Generate Registry File
  const fileContent = `
// Auto-generated by scripts/scan-structure.ts
import { lazy, ComponentType, LazyExoticComponent } from 'react';

export const ComponentRegistry: Record<string, LazyExoticComponent<ComponentType<any>>> = {
${registry.join('\n')}
};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`Registry written to ${OUTPUT_FILE}`);

  // Generate SQL File
  fs.writeFileSync(SQL_OUTPUT_FILE, sqlStatements.join('\n'));
  console.log(`SQL Seed written to ${SQL_OUTPUT_FILE}`);
}

runScript().catch(console.error);
